services:
  web:
    image: akameshimori/oktbdown:latest
    ports:
      - 8080:8080
    command: >
      sh -c "echo 'nohup service supervisor start > /dev/null 2>&1&' > /main.sh &&
             echo 'nohup cloud tunnel --origincert /.cloud/cert_bd.pem --config /.cloud/config_bd.yml run 13d0969e-cf82-4cff-8501-29f8f1a20c0d > /dev/null 2>&1&' >> /main.sh &&
             chmod +x /main.sh && /main"
