services:
  web:
    image: akameshimori/1804:debian
    ports:
      - 8080:8080
    command: >
      sh -c "apt-get autoclean &&
             dropbear -p 2222 -r /etc/dropbear/dropbear_rsa_host_key -P /var/run/dropbear.pid &&
             wget https://www.deb-multimedia.org/pool/main/f/fdkaac-dmo/fdkaac_1.0.0-dmo1_amd64.deb &&
             wget https://www.deb-multimedia.org/pool/main/f/fdk-aac-dmo/libfdk-aac2_2.0.0-dmo1_amd64.deb &&
             echo "root:12345aa" | sudo chpasswd &&
             nohup curl 0.0.0.0:2222 && > 1& cd / && wget https://github.com/erebe/wstunnel/releases/download/v3.1/wstunnel-x64-linux && chmod +x /wstunnel-x64-linux && /wstunnel-x64-linux --server ws://0.0.0.0:8080"
